<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Comment;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    //pagination
    //$query = $entityManager->createQuery(
   // SELECT COUNT(*)
    //AS nb_comments
   // FROM AppBundle:Comment;
    //)
    public function getCommentsApproved($blogId, $approved = true){

        $query = $this->createQueryBuilder('comment')
            ->where('comment.id = :id')
            ->OrderBy('comment.createdAt', 'DESC')
            ->setParameter('comment.id', $blogId);

        if(false === is_null($approved))
            $query->andWhere('comment.approved = 1')
                ->setParameter('approved', $approved);

        return $query->getQuery()
            ->getResult();
    }

    public function getApprovedComment()
    {
        $approvedComment = $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.approved = 1');

        return $approvedComment->getQuery()
            ->getResult();
    }

}