<?php

namespace AppBundle\Repository;

//use AppBundle\Entity\Comment;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    //pagination
    //$query = $entityManager->createQuery(
   // SELECT COUNT(*)
    //AS nb_comments
   // FROM AppBundle:Comment;
    //)
}